// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=exe, use-js-string=true, version=5.8.2
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(d){"use strict";var
db=d,bN="Sys_error",o=0x80,bw="ENOTEMPTY",bz="Invalid_argument",bM="EEXIST",aB="mkdir",bs=": file descriptor already closed",av="EBADF",ay=" : flags Open_text and Open_binary are not compatible",bF="window",O=1024,aA="fs",ac="Map.bal",aI="Promise",bE="/static/",bv="Stack_overflow",ax=": Not a directory",aF="ENOENT",bU="Pervasives.do_at_exit",aC=" : flags Open_rdonly and Open_wronly are not compatible",bL="Undefined_recursive_module",bT=65536,bD="Assert_failure",by=512,bK=0x800,bR="Match_failure",bS="closedir",bt="error",bu=" : is a directory",bC=0xdfff,bJ="Division_by_zero",bX="End_of_file",bB=": closedir failed",G=0x3f,bW="Out_of_memory",f="",az="rmdir",bI="([^/]+)",br="jsError",bA="Not_found",aa='"',aE=" : file already exists",bQ="fd ",aH="Failure",ab=": No such file or directory",aD=128,ad="Unix.Unix_error",bq=0xdc00,bH="Sys_blocked_io",bV="^",h=248,aG="ENOTDIR",bP=0xe0,n="/",aw="index out of bounds",bx=24029,bG="to_js",bO=0xf0;function
cH(a,b,c,d,e){if(d<=b)for(var
f=1;f<=e;f++)c[d+f]=a[b+f];else
for(var
f=e;f>=1;f--)c[d+f]=a[b+f];return 0}function
cI(a){return a[1]}function
R(d,c){var
f=d.l>=0?d.l:d.l=d.length,e=c.length,b=f-e;if(b==0)return d.apply(null,c);else if(b<0){var
a=d.apply(null,c.slice(0,f));if(typeof
a!=="function")return a;return R(a,c.slice(f))}else{switch(b){case
1:{var
a=function(a){var
f=new
Array(e+1);for(var
b=0;b<e;b++)f[b]=c[b];f[e]=a;return d.apply(null,f)};break}case
2:{var
a=function(a,b){var
g=new
Array(e+2);for(var
f=0;f<e;f++)g[f]=c[f];g[e]=a;g[e+1]=b;return d.apply(null,g)};break}default:var
a=function(){var
e=arguments.length==0?1:arguments.length,b=new
Array(c.length+e);for(var
a=0;a<c.length;a++)b[a]=c[a];for(var
a=0;a<arguments.length;a++)b[c.length+a]=arguments[a];return R(d,b)}}a.l=b;return a}}function
dc(a){var
b=d.process;if(b&&b.env&&b.env[a]!=undefined)return b.env[a];if(d.jsoo_static_env&&d.jsoo_static_env[a])return d.jsoo_static_env[a]}var
aQ=0;(function(){var
c=dc("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(",");for(var
a=0;a<b.length;a++)if(b[a]=="b"){aQ=1;break}else if(b[a].startsWith("b="))aQ=+b[a].slice(2);else
continue}}());var
j=[0];function
cO(a,b){if(!a.js_error||b||a[0]==h)a.js_error=new
d.Error("Js exception containing backtrace");return a}function
B(a,b){return aQ?cO(a,b):a}function
c5(a,b){throw B([0,a,b])}function
s(a){return a}function
aP(a,b){c5(a,s(b))}function
ag(a){aP(j.Invalid_argument,a)}function
bZ(){ag(aw)}function
z(a,b){if(b>>>0>=a.length-1)bZ();return a}function
aL(a){if(!j.Failure)j.Failure=[h,s(aH),-3];aP(j.Failure,a)}function
aS(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
ca(a){for(var
k=f,d=f,h,g,i,b,c=0,j=a.length;c<j;c++){g=a.charCodeAt(c);if(g<o){for(var
e=c+1;e<j&&(g=a.charCodeAt(e))<o;e++);if(e-c>by){d.substr(0,1);k+=d;d=f;k+=a.slice(c,e)}else
d+=a.slice(c,e);if(e==j)break;c=e}b=1;if(++c<j&&((i=a.charCodeAt(c))&-64)==aD){h=i+(g<<6);if(g<bP){b=h-0x3080;if(b<o)b=1}else{b=2;if(++c<j&&((i=a.charCodeAt(c))&-64)==aD){h=i+(h<<6);if(g<bO){b=h-0xe2080;if(b<bK||b>=0xd7ff&&b<0xe000)b=2}else{b=3;if(++c<j&&((i=a.charCodeAt(c))&-64)==aD&&g<0xf5){b=i-0x3c82080+(h<<6);if(b<0x10000||b>0x10ffff)b=3}}}}}if(b<4){c-=b;d+="\ufffd"}else if(b>0xffff)d+=String.fromCharCode(0xd7c0+(b>>10),bq+(b&0x3FF));else
d+=String.fromCharCode(b);if(d.length>O){d.substr(0,1);k+=d;d=f}}return k+d}function
aO(a){if(aS(a))return a;return ca(a)}function
V(){return typeof
d.process!=="undefined"&&typeof
d.process.versions!=="undefined"&&typeof
d.process.versions.node!=="undefined"}function
dd(){function
a(a){if(a.charAt(0)===n)return[f,a.substring(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||f,e=Boolean(c&&c.charAt(1)!==":");if(Boolean(b[2]||e)){var
d=b[1]||f,g=b[2]||f;return[d,a.substring(d.length+g.length)]}return}return V()&&d.process&&d.process.platform?d.process.platform==="win32"?b:a:a}var
aT=dd();function
b_(a){return a.slice(-1)!==n?a+n:a}if(V()&&d.process&&d.process.cwd)var
S=d.process.cwd().replace(/\\/g,n);else
var
S="/static";S=b_(S);function
cX(a){a=aO(a);if(!aT(a))a=S+a;var
e=aT(a),d=e[1].split(n),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}function
da(a){for(var
g=f,c=g,b,i,d=0,h=a.length;d<h;d++){b=a.charCodeAt(d);if(b<o){for(var
e=d+1;e<h&&(b=a.charCodeAt(e))<o;e++);if(e-d>by){c.substr(0,1);g+=c;c=f;g+=a.slice(d,e)}else
c+=a.slice(d,e);if(e==h)break;d=e}if(b<bK){c+=String.fromCharCode(0xc0|b>>6);c+=String.fromCharCode(o|b&G)}else if(b<0xd800||b>=bC)c+=String.fromCharCode(bP|b>>12,o|b>>6&G,o|b&G);else if(b>=0xdbff||d+1==h||(i=a.charCodeAt(d+1))<bq||i>bC)c+="\xef\xbf\xbd";else{d++;b=(b<<10)+i-0x35fdc00;c+=String.fromCharCode(bO|b>>18,o|b>>12&G,o|b>>6&G,o|b&G)}if(c.length>O){c.substr(0,1);g+=c;c=f}}return g+c}function
I(a){return aS(a)?s(a):s(da(a))}var
de=["E2BIG","EACCES","EAGAIN",av,"EBUSY","ECHILD","EDEADLK","EDOM",bM,"EFAULT","EFBIG","EINTR","EINVAL","EIO","EISDIR","EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",aF,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",aG,bw,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS","ESPIPE","ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
t(a,b,c,d){var
e=de.indexOf(a);if(e<0){if(d==null)d=-9999;e=[0,d]}var
g=[e,I(b||f),I(c||f)];return g}var
b6={};function
x(a){return b6[a]}function
r(a,b){throw B([0,a].concat(b))}function
c8(a,b){if(a==0)return f;if(b.repeat)return b.repeat(a);var
d=f,c=0;for(;;){if(a&1)d+=b;a>>=1;if(a==0)return d;b+=b;c++;if(c==9)b.slice(0,1)}}function
ak(a,b,c){var
d=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return d.apply(null,a);var
e=f;for(;0<c;b+=O,c-=O)e+=d.apply(null,a.slice(b,b+Math.min(c,O)));return e}function
cM(a){if(a.t==2)a.c+=c8(a.l-a.c.length,"\0");else
a.c=ak(a.c,0,a.c.length);a.t=0}function
q(a,b,c){this.t=a;this.c=b;this.l=c}q.prototype.toString=function(){switch(this.t){case
9:return this.c;default:cM(this);case
0:if(aS(this.c)){this.t=9;return this.c}this.t=8;case
8:return this.c}};q.prototype.toUtf16=function(){var
a=this.toString();if(this.t==9)return a;return ca(a)};q.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
q(this.t,a,this.l)};function
cS(a){return a
instanceof
q}function
cT(a){return typeof
a==="string"&&!/[^\x00-\xff]/.test(a)}function
aJ(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
q(4,a,a.length)}function
b0(a){return new
q(0,a,a.length)}function
ah(a){return a}function
ae(a){return b0(ah(a))}function
e(a){aP(j.Sys_error,a)}function
b7(a){e(a+ab)}function
aK(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
b$(a){if(a.t!=4)aK(a);return a.c}function
A(a){if(a<0)ag("Bytes.create");return new
q(a?2:9,f,a)}function
cY(a){return a.l}function
Q(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?ak(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else if(c.t==2&&d==c.c.length){c.c+=a.t==4?ak(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)aK(c);var
g=a.c,h=c.c;if(a.t==4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
bY(){}function
i(a){this.data=a}i.prototype=new
bY();i.prototype.constructor=i;i.prototype.truncate=function(a){var
b=this.data;this.data=A(a|0);Q(b,0,this.data,0,a)};i.prototype.length=function(){return cY(this.data)};i.prototype.write=function(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=A(a+d),g=this.data;this.data=f;Q(g,0,this.data,0,e)}Q(aJ(b),c,this.data,a,d);return 0};i.prototype.read=function(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d){var
f=A(d|0);Q(this.data,a,f,0,d);b.set(b$(f),c)}return d};function
y(a,b,c){this.file=b;this.name=a;this.flags=c}y.prototype.err_closed=function(){e(this.name+bs)};y.prototype.length=function(){if(this.file)return this.file.length();this.err_closed()};y.prototype.write=function(a,b,c,d){if(this.file)return this.file.write(a,b,c,d);this.err_closed()};y.prototype.read=function(a,b,c,d){if(this.file)return this.file.read(a,b,c,d);this.err_closed()};y.prototype.close=function(){this.file=undefined};function
c(a,b){this.content={};this.root=a;this.lookupFun=b}c.prototype.nm=function(a){return this.root+a};c.prototype.create_dir_if_needed=function(a){var
d=a.split(n),c=f;for(var
b=0;b<d.length-1;b++){c+=d[b]+n;if(this.content[c])continue;this.content[c]=Symbol("directory")}};c.prototype.slash=function(a){return/\/$/.test(a)?a:a+n};c.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(s(this.root),s(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
i(ae(b[1]))}}};c.prototype.exists=function(a){if(a==f)return 1;var
b=this.slash(a);if(this.content[b])return 1;this.lookup(a);return this.content[a]?1:0};c.prototype.isFile=function(a){return this.exists(a)&&!this.is_dir(a)?1:0};c.prototype.mkdir=function(a,b,c){var
g=c&&x(ad);if(this.exists(a))if(g)r(g,t(bM,aB,this.nm(a)));else
e(a+": File exists");var
d=/^(.*)\/[^/]+/.exec(a);d=d&&d[1]||f;if(!this.exists(d))if(g)r(g,t(aF,aB,this.nm(d)));else
e(d+ab);if(!this.is_dir(d))if(g)r(g,t(aG,aB,this.nm(d)));else
e(d+ax);this.create_dir_if_needed(this.slash(a))};c.prototype.rmdir=function(a,b){var
c=b&&x(ad),d=a==f?f:this.slash(a),h=new
RegExp(bV+d+bI);if(!this.exists(a))if(c)r(c,t(aF,az,this.nm(a)));else
e(a+ab);if(!this.is_dir(a))if(c)r(c,t(aG,az,this.nm(a)));else
e(a+ax);for(var
g
in
this.content)if(g.match(h))if(c)r(c,t(bw,az,this.nm(a)));else
e(this.nm(a)+": Directory not empty");delete
this.content[d]};c.prototype.readdir=function(a){var
h=a==f?f:this.slash(a);if(!this.exists(a))e(a+ab);if(!this.is_dir(a))e(a+ax);var
i=new
RegExp(bV+h+bI),d={},c=[];for(var
g
in
this.content){var
b=g.match(i);if(b&&!d[b[1]]){d[b[1]]=true;c.push(b[1])}}return c};c.prototype.opendir=function(a,b){var
c=b&&x(ad),d=this.readdir(a),f=false,g=0;return{readSync:function(){if(f)if(c)r(c,t(av,bS,this.nm(a)));else
e(a+bB);if(g==d.length)return null;var
b=d[g];g++;return{name:b}},closeSync:function(){if(f)if(c)r(c,t(av,bS,this.nm(a)));else
e(a+bB);f=true;d=[]}}};c.prototype.is_dir=function(a){if(a==f)return true;var
b=this.slash(a);return this.content[b]?1:0};c.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};c.prototype.open=function(a,b){var
c;if(b.rdonly&&b.wronly)e(this.nm(a)+aC);if(b.text&&b.binary)e(this.nm(a)+ay);this.lookup(a);if(this.content[a]){if(this.is_dir(a))e(this.nm(a)+bu);if(b.create&&b.excl)e(this.nm(a)+aE);c=this.content[a];if(b.truncate)c.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
i(A(0));c=this.content[a]}else
b7(this.nm(a));return new
y(this.nm(a),c,b)};c.prototype.open=function(a,b){var
c;if(b.rdonly&&b.wronly)e(this.nm(a)+aC);if(b.text&&b.binary)e(this.nm(a)+ay);this.lookup(a);if(this.content[a]){if(this.is_dir(a))e(this.nm(a)+bu);if(b.create&&b.excl)e(this.nm(a)+aE);c=this.content[a];if(b.truncate)c.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
i(A(0));c=this.content[a]}else
b7(this.nm(a));return new
y(this.nm(a),c,b)};c.prototype.register=function(a,b){var
c;if(this.content[a])e(this.nm(a)+aE);if(cS(b))c=new
i(b);if(cT(b))c=new
i(ae(b));else if(b
instanceof
Array)c=new
i(aJ(b));else if(typeof
b==="string")c=new
i(b0(b));else if(b.toString){var
d=ae(I(b.toString()));c=new
i(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
e(this.nm(a)+" : registering file with invalid content type")};c.prototype.constructor=c;function
ai(a){return a.length}function
b9(a,b){return a.charCodeAt(b)}function
di(a){var
d=ai(a),c=new
Uint8Array(d),b=0;for(;b<d;b++)c[b]=b9(a,b);return c}function
cK(){ag(aw)}function
cL(a,b,c){c&=0xff;if(a.t!=4){if(b==a.c.length){a.c+=String.fromCharCode(c);if(b+1==a.l)a.t=0;return 0}aK(a)}a.c[b]=c;return 0}function
dg(a,b,c){if(b>>>0>=a.l)cK();return cL(a,b,c)}function
p(a,b){this.fs=require(aA);this.fd=a;this.flags=b}p.prototype=new
bY();p.prototype.constructor=p;p.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(f){e(f.toString())}};p.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(f){e(f.toString())}};p.prototype.write=function(a,b,c,d){try{if(this.flags.isCharacterDevice)this.fs.writeSync(this.fd,b,c,d);else
this.fs.writeSync(this.fd,b,c,d,a)}catch(f){e(f.toString())}return 0};p.prototype.read=function(a,b,c,d){try{if(this.flags.isCharacterDevice)var
f=this.fs.readSync(this.fd,b,c,d);else
var
f=this.fs.readSync(this.fd,b,c,d,a);return f}catch(f){e(f.toString())}};p.prototype.close=function(){try{this.fs.closeSync(this.fd);return 0}catch(f){e(f.toString())}};function
b(a){this.fs=require(aA);this.root=a}b.prototype.nm=function(a){return this.root+a};b.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}};b.prototype.isFile=function(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){e(f.toString())}};b.prototype.mkdir=function(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.rmdir=function(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.readdir=function(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){e(f.toString())}};b.prototype.unlink=function(a,b){try{var
c=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return c}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.open=function(a,b,c){var
d=require("constants"),e=0;for(var
h
in
b)switch(h){case"rdonly":e|=d.O_RDONLY;break;case"wronly":e|=d.O_WRONLY;break;case"append":e|=d.O_WRONLY|d.O_APPEND;break;case"create":e|=d.O_CREAT;break;case"truncate":e|=d.O_TRUNC;break;case"excl":e|=d.O_EXCL;break;case"binary":e|=d.O_BINARY;break;case"text":e|=d.O_TEXT;break;case"nonblock":e|=d.O_NONBLOCK;break}try{var
f=this.fs.openSync(this.nm(a),e),g=this.fs.lstatSync(this.nm(a)).isCharacterDevice();b.isCharacterDevice=g;return new
p(f,b)}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.rename=function(a,b,c){try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.stat=function(a,b){try{var
c=this.fs.statSync(this.nm(a));return this.stats_from_js(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.lstat=function(a,b){try{var
c=this.fs.lstatSync(this.nm(a));return this.stats_from_js(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.symlink=function(a,b,c,d){try{this.fs.symlinkSync(this.nm(b),this.nm(c),a?"dir":"file");return 0}catch(f){this.raise_nodejs_error(f,d)}};b.prototype.readlink=function(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return I(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.opendir=function(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.raise_nodejs_error=function(a,b){var
c=x(ad);if(b&&c){var
d=t(a.code,a.syscall,a.path,a.errno);r(c,d)}else
e(a.toString())};b.prototype.stats_from_js=function(a){var
b;if(a.isFile())b=0;else if(a.isDirectory())b=1;else if(a.isCharacterDevice())b=2;else if(a.isBlockDevice())b=3;else if(a.isSymbolicLink())b=4;else if(a.isFIFO())b=5;else if(a.isSocket())b=6;return[0,a.dev,a.ino,b,a.mode,a.nlink,a.uid,a.gid,a.rdev,a.size,a.atimeMs,a.mtimeMs,a.ctimeMs]};b.prototype.constructor=b;function
b2(a){var
b=aT(a);if(!b)return;return b[0]+n}var
aj=b2(S)||aL("unable to compute caml_root"),J=[];if(V())J.push({path:aj,device:new
b(aj)});else
J.push({path:aj,device:new
c(aj)});J.push({path:bE,device:new
c(bE)});function
cc(a){var
i=cX(a),a=i.join(n),h=b_(a),d;for(var
g=0;g<J.length;g++){var
c=J[g];if(h.search(c.path)==0&&(!d||d.path.length<c.path.length))d={path:c.path,device:c.device,rest:a.substring(c.path.length,a.length)}}if(!d&&V()){var
f=b2(a);if(f&&f.match(/^[a-zA-Z]:\/$/)){var
c={path:f,device:new
b(f)};J.push(c);d={path:c.path,device:c.device,rest:a.substring(c.path.length,a.length)}}}if(d)return d;e("no device found for "+h)}function
cN(a,b){var
c=cc(a);if(!c.device.register)aL("cannot register file");c.device.register(c.rest,b);return 0}function
cb(a,b){var
a=s(a),b=s(b);return cN(a,b)}function
cQ(){var
b=d.caml_fs_tmp;if(b)for(var
a=0;a<b.length;a++)cb(b[a].name,b[a].content);d.jsoo_create_file=cb;d.caml_fs_tmp=[];return 0}function
cR(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
T(a){return aO(a)}function
cV(a){return+a}function
aM(a){return I(a)}var
af=R;function
aN(a,b){return function(){var
f=arguments.length,d=new
Array(a),e=Math.min(arguments.length,a);for(var
c=0;c<e;c++)d[c]=arguments[c];return af(b,d)}}function
cW(a){var
c=0;for(var
b=a.length-1;b>=0;b--){var
d=a[b];c=[0,d,c]}return c}function
U(a,b){if(a<0)bZ();var
a=a+1|0,c=new
Array(a);c[0]=0;for(var
d=1;d<a;d++)c[d]=b;return c}var
w=new
Array();function
b3(a){return w[a]}function
H(a){var
b=b3(a);if(!b.opened)e("Cannot flush a closed channel");if(!b.buffer||b.buffer_curr==0)return 0;if(b.output)b.output(ak(b.buffer,0,b.buffer_curr));else
b.file.write(b.offset,b.buffer,0,b.buffer_curr);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}function
c$(a,b){if(b.name)try{var
d=require(aA),c=d.openSync(b.name,"rs");return new
p(c,b)}catch(f){}return new
p(a,b)}var
al=new
Array(3);function
P(a,b){i.call(this,A(0));this.log=function(a){return 0};if(a==1&&typeof
console.log=="function")this.log=console.log;else if(a==2&&typeof
console.error=="function")this.log=console.error;else if(typeof
console.log=="function")this.log=console.log;this.flags=b}P.prototype.length=function(){return 0};P.prototype.write=function(a,b,c,d){if(this.log){if(d>0&&c>=0&&c+d<=b.length&&b[c+d-1]==10)d--;var
f=A(d);Q(aJ(b),c,f,0,d);this.log(f.toUtf16());return 0}e(this.fd+bs)};P.prototype.read=function(a,b,c,d){e(this.fd+": file descriptor is write only")};P.prototype.close=function(){this.log=undefined};function
am(a,b){if(b==undefined)b=al.length;al[b]=a;return b|0}function
dh(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}if(d.rdonly&&d.wronly)e(ah(a)+aC);if(d.text&&d.binary)e(ah(a)+ay);var
f=cc(a),g=f.device.open(f.rest,d);return am(g,undefined)}(function(){function
a(a,b){return V()?c$(a,b):new
P(a,b)}am(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:true}),0);am(a(1,{buffered:2,wronly:1,isCharacterDevice:true}),1);am(a(2,{buffered:2,wronly:1,isCharacterDevice:true}),2)}());function
cZ(a){var
b=al[a];if(b.flags.wronly)e(bQ+a+" is writeonly");var
d=null,c={file:b,offset:b.flags.append?b.length():0,fd:a,opened:true,out:false,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(bT),refill:d};w[c.fd]=c;return c.fd}function
b4(a){var
b=al[a];if(b.flags.rdonly)e(bQ+a+" is readonly");var
d=b.flags.buffered!==undefined?b.flags.buffered:1,c={file:b,offset:b.flags.append?b.length():0,fd:a,opened:true,out:true,buffer_curr:0,buffer:new
Uint8Array(bT),buffered:d};w[c.fd]=c;return c.fd}function
c0(){var
b=0;for(var
a=0;a<w.length;a++)if(w[a]&&w[a].opened&&w[a].out)b=[0,w[a].fd,b];return b}function
c3(a,b,c,d){var
f=b3(a);if(!f.opened)e("Cannot output to a closed channel");b=b.subarray(c,c+d);if(f.buffer_curr+b.length>f.buffer.length){var
h=new
Uint8Array(f.buffer_curr+b.length);h.set(f.buffer);f.buffer=h}switch(f.buffered){case
0:f.buffer.set(b,f.buffer_curr);f.buffer_curr+=b.length;H(a);break;case
1:f.buffer.set(b,f.buffer_curr);f.buffer_curr+=b.length;if(f.buffer_curr>=f.buffer.length)H(a);break;case
2:var
g=b.lastIndexOf(10);if(g<0){f.buffer.set(b,f.buffer_curr);f.buffer_curr+=b.length;if(f.buffer_curr>=f.buffer.length)H(a)}else{f.buffer.set(b.subarray(0,g+1),f.buffer_curr);f.buffer_curr+=g+1;H(a);f.buffer.set(b.subarray(g+1),f.buffer_curr);f.buffer_curr+=b.length-g-1}break}return 0}function
c1(a,b,c,d){var
b=b$(b);return c3(a,b,c,d)}function
b5(a,b,c,d){return c1(a,ae(b),c,d)}function
c2(a,b){var
c=s(String.fromCharCode(b));b5(a,c,0,1);return 0}function
c4(a,b){var
d=new
Array(b+1);d[0]=a;for(var
c=1;c<=b;c++)d[c]=0;return d}function
cJ(a){var
c={};if(a)for(var
b=1;b<a.length;b++)c[aO(a[b][1])]=a[b][2];return c}function
l(a,b,c){if(c){var
e=c;if(d.toplevelReloc)a=af(d.toplevelReloc,[e]);else if(j.symbols){if(!j.symidx)j.symidx=cJ(j.symbols);var
f=j.symidx[e];if(f>=0)a=f;else
aL("caml_register_global: cannot locate "+e)}}j[a+1]=b;if(c)j[c]=b}function
c6(a,b){b6[ah(a)]=b;return 0}function
b8(a,b){return a<b?-1:a>b?1:0}function
c9(){ag(aw)}function
c_(a,b){if(b>>>0>=ai(a))c9();return b9(a,b)}function
aR(a){{if(a
instanceof
Array)return a;var
b;if(d.RangeError&&a
instanceof
d.RangeError&&a.message&&a.message.match(/maximum call stack/i))b=j.Stack_overflow;else if(d.InternalError&&a
instanceof
d.InternalError&&a.message&&a.message.match(/too much recursion/i))b=j.Stack_overflow;else if(a
instanceof
d.Error&&x(br))b=[0,x(br),a];else
b=[0,j.Failure,I(String(a))];if(a
instanceof
d.Error)b.js_error=a;return b}}function
cU(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}function
cP(a){var
b=f;if(a[0]==0){b+=a[1][1];if(a.length==3&&a[2][0]==0&&cU(a[1]))var
e=a[2],g=1;else
var
g=2,e=a;b+="(";for(var
d=g;d<e.length;d++){if(d>g)b+=", ";var
c=e[d];if(typeof
c=="number")b+=c.toString();else if(c
instanceof
q)b+=aa+c.toString()+aa;else if(typeof
c=="string")b+=aa+c.toString()+aa;else
b+="_"}b+=")"}else if(a[0]==h)b+=a[1];return b}function
b1(a){if(a
instanceof
Array&&(a[0]==0||a[0]==h)){var
c=x("Printexc.handle_uncaught_exception");if(c)af(c,[a,false]);else{var
d=cP(a),b=x(bU);if(b)af(b,[0]);console.error("Fatal error: exception "+d);if(a.js_error)throw a.js_error}}else
throw a}function
c7(){var
c=d.process;if(c&&c.on)c.on("uncaughtException",function(a,b){b1(a);c.exit(2)});else if(d.addEventListener)d.addEventListener(bt,function(a){if(a.error)b1(a.error)})}c7();function
k(a,b){return(a.l>=0?a.l:a.l=a.length)==1?a(b):R(a,[b])}function
N(a,b,c){return(a.l>=0?a.l:a.l=a.length)==2?a(b,c):R(a,[b,c])}var
df=undefined;cQ();var
aV=[h,bN,-2],aU=[h,bz,-4],W=[h,bA,-7],bf=bG,D=[0,bG];l(11,[h,bL,-12],bL);l(10,[h,bD,-11],bD);l(9,[h,bH,-10],bH);l(8,[h,bv,-9],bv);l(7,[h,bR,-8],bR);l(6,W,bA);l(5,[h,bJ,-6],bJ);l(4,[h,bX,-5],bX);l(3,aU,bz);l(2,[h,aH,-3],aH);l(1,aV,bN);l(0,[h,bW,-1],bW);function
C(a){throw B([0,aU,a],1)}cZ(0);var
an=b4(1);b4(2);function
u(a){b5(an,a,0,ai(a));c2(an,10);H(an);return}var
cd=[0,function(a){var
b=c0(0);for(;;){if(!b)return 0;var
d=b[2],e=b[1];try{H(e)}catch(f){var
c=aR(f);if(c[1]!==aV)throw B(c,0)}b=d}}];function
aX(a){return k(cI(cd),0)}c6(bU,aX);function
ap(a,b){if(!b)return 0;var
f=b[2],h=b[1];if(!f)return[0,k(a,h),0];var
m=f[2],n=f[1],o=k(a,h),i=[0,k(a,n),bx],e=i,d=1,c=m;for(;;){if(c){var
g=c[2],j=c[1];if(g){var
p=g[2],q=g[1],r=k(a,j),l=[0,k(a,q),bx];e[1+d]=[0,r,l];e=l;d=1;c=p;continue}e[1+d]=[0,k(a,j),0]}else
e[1+d]=0;return[0,o,i]}}function
a1(a){var
b=a.length-2|0,c=0;for(;;){if(0>b)return c;var
d=[0,a[1+b],c];b=b-1|0;c=d}}function
a2(a){if(!a)return[0];var
d=0,c=a,g=a[2],h=a[1];for(;;){if(!c)break;d=d+1|0;c=c[2]}var
f=U(d,h),e=1,b=g;for(;;){if(!b)return f;var
i=b[2];f[1+e]=b[1];e=e+1|0;b=i}}var
cl=ac,cm=ac,cn=ac,co=ac;function
ar(m){function
h(a){return a?a[5]:0}function
e(a,b,c,d){var
e=h(a),f=h(d),g=f<=e?e+1|0:f+1|0;return[0,a,b,c,d,g]}function
i(a,b,c,d){var
i=a?a[5]:0,j=d?d[5]:0;if((j+2|0)<i){if(!a)return C(cm);var
f=a[4],m=a[3],n=a[2],k=a[1],q=h(f);if(q<=h(k))return e(k,n,m,e(f,b,c,d));if(!f)return C(cl);var
r=f[3],s=f[2],t=f[1],u=e(f[4],b,c,d);return e(e(k,n,m,t),s,r,u)}if((i+2|0)>=j){var
A=j<=i?i+1|0:j+1|0;return[0,a,b,c,d,A]}if(!d)return C(co);var
l=d[4],o=d[3],p=d[2],g=d[1],v=h(g);if(v<=h(l))return e(e(a,b,c,g),p,o,l);if(!g)return C(cn);var
w=g[3],x=g[2],y=g[1],z=e(g[4],p,o,l);return e(e(a,b,c,y),x,w,z)}function
f(a,b,c){if(!c)return[0,0,a,b,0,1];var
d=c[4],g=c[3],h=c[2],e=c[1],n=c[5],j=N(m[1],a,h);if(0===j)return g===b?c:[0,e,a,b,d,n];if(0<=j){var
k=f(a,b,d);return d===k?c:i(e,h,g,k)}var
l=f(a,b,e);return e===l?c:i(l,h,g,d)}return[0,0,f,,,,,,,,,,,,,,,function(a,b){var
c=b;for(;;){if(!c)throw B(W,1);var
e=c[4],f=c[3],g=c[1],d=N(m[1],a,c[2]);if(0===d)return f;var
h=0<=d?e:g;c=h}}]}function
a3(a){var
b=[0,0],d=ai(a)-1|0,e=0;if(d>=0){var
c=e;for(;;){var
g=c_(a,c);b[1]=(223*b[1]|0)+g|0;var
h=c+1|0;if(d===c)break;c=h}}b[1]=b[1]&2147483647;var
f=1073741823<b[1]?b[1]+2147483648|0:b[1];return f}var
a4=ar([0,b8]),Y=ar([0,b8]),Z=ar([0,cR]),a5=c4(0,0),cg="Array.blit",cp=2,cq=[0,0];function
a6(a){return 2<a?a6((a+1|0)/2|0)*2|0:a}function
a7(a){cq[1]++;var
c=a.length-1,d=U((c*2|0)+2|0,a5);z(d,0)[1]=c;var
g=((a6(c)*32|0)/8|0)-1|0;z(d,1)[2]=g;var
e=c-1|0,h=0;if(e>=0){var
b=h;for(;;){var
f=(b*2|0)+3|0,i=z(a,b)[1+b];z(d,f)[1+f]=i;var
j=b+1|0;if(e===b)break;b=j}}return[0,cp,d,Y[1],Z[1],0,0,a4[1],0]}function
as(a,b){var
c=a[2].length-1;if(c<b){var
d=U(b,a5),e=a[2];a:{if(0<=c&&(e.length-1-c|0)>=0&&(d.length-1-c|0)>=0){cH(e,0,d,0,c);break a}C(cg)}a[2]=d}return}var
bb=null,g=db,cf="Array.init";function
bc(a,b){var
e=b.length-1,d=new
g["Array"](e),f=e-1|0,h=0;if(f>=0){var
c=h;for(;;){d[c]=k(a,z(b,c)[1+c]);var
i=c+1|0;if(f===c)break;c=i}}return d}function
bd(j,b){function
g(a){return k(j,b[a|0])}var
c=b["length"]-0|0;if(0===c)var
d=[0];else if(0<=c){var
e=U(c,g(0)),f=c-1|0,h=1;if(f>=1){var
a=h;for(;;){e[1+a]=g(a);var
i=a+1|0;if(f===a)break;a=i}}var
d=e}else
var
d=C(cf);return a1(d)}function
at(a){return 0}var
cv=f,cF="[Service Worker] cached",cG="[Service Worker] fetching",cE="[Service Worker] activate",cD="[Service Worker] failed to cache ressources",cC="[Service Worker] install",cB=cW([n,"/app.js","/service-worker.js","/style.css","/index.html","/manifest.json","/favicon.ico","/icons/icon-192x192.png","/icons/icon-512x512.png","/data/french.txt","/data/italian.txt","/data/russian.txt","/data/british.txt","/data/american.txt"]),cr=[0,0],cu=undefined;if(0===D)var
a=a7([0]);else{var
aq=D.length-1;if(0===aq)var
a$=[0];else{var
aY=U(aq,a3(D[1])),aZ=aq-1|0,ch=1;if(aZ>=1){var
K=ch;for(;;){aY[1+K]=a3(D[1+K]);var
ci=K+1|0;if(aZ===K)break;K=ci}}var
a$=aY}var
M=a7(a$),a0=D.length-2|0,cj=0;if(a0>=0){var
L=cj;for(;;){var
ba=(L*2|0)+2|0;M[3]=Y[2].call(null,D[1+L],ba,M[3]);M[4]=Z[2].call(null,ba,1,M[4]);var
ck=L+1|0;if(a0===L)break;L=ck}}var
a=M}try{var
ct=a4[17].call(null,cv,a[7]),be=ct}catch(f){var
a_=aR(f);if(a_!==W)throw B(a_,0);var
a9=a[1];a[1]=a9+1|0;var
be=a9}try{var
cs=Y[17].call(null,bf,a[3]),E=cs}catch(f){var
a8=aR(f);if(a8!==W)throw B(a8,0);var
_=a[2].length-1;as(a,_+1|0);a[3]=Y[2].call(null,bf,_,a[3]);a[4]=Z[2].call(null,_,1,a[4]);var
E=_}function
bg(a){return a[1+be]}cr[1]++;if(Z[17].call(null,E,a[4])){as(a,E+1|0);z(a[2],E)[1+E]=bg}else
a[6]=[0,[0,E,bg],a[6]];var
X=a[8],ao=0;for(;;){if(!X)break;var
ce=[0,X[1],ao];X=X[2];ao=ce}a[8]=ao;as(a,3+((z(a[2],1)[2]*16|0)/32|0)|0);g[bF];g["document"];function
bh(b){return function(a){b.log(a);return}}var
bi=g["console"];function
cw(a){if(typeof
a!=="number")return T(a[1]);var
b=a;if(90<=b){if(135<=b)switch(b){case
135:return"result";case
136:return"resume";case
137:return"scroll";case
138:return"seeked";case
139:return"seeking";case
140:return"select";case
141:return"selectionchange";case
142:return"selectstart";case
143:return"show";case
144:return"slotchange";case
145:return"soundend";case
146:return"soundstart";case
147:return"speechend";case
148:return"speechstart";case
149:return"stalled";case
150:return"start";case
151:return"storage";case
152:return"submit";case
153:return"success";case
154:return"suspend";case
155:return"SVGAbort";case
156:return"SVGError";case
157:return"SVGLoad";case
158:return"SVGResize";case
159:return"SVGScroll";case
160:return"SVGUnload";case
161:return"SVGZoom";case
162:return"timeout";case
163:return"timeupdate";case
164:return"touchcancel";case
165:return"touchend";case
166:return"touchmove";case
167:return"touchstart";case
168:return"transitionend";case
169:return"unload";case
170:return"updateready";case
171:return"upgradeneeded";case
172:return"userproximity";case
173:return"versionchange";case
174:return"visibilitychange";case
175:return"voiceschanged";case
176:return"volumechange";case
177:return"waiting";default:return"wheel"}switch(b){case
90:return"lostpointercapture";case
91:return"mark";case
92:return"message";case
93:return"messageerror";case
94:return"mousedown";case
95:return"mouseenter";case
96:return"mouseleave";case
97:return"mousemove";case
98:return"mouseout";case
99:return"mouseover";case
100:return"mouseup";case
101:return"nomatch";case
102:return"notificationclick";case
103:return"noupdate";case
104:return"obsolete";case
105:return"offline";case
106:return"online";case
107:return"open";case
108:return"orientationchange";case
109:return"pagehide";case
110:return"pageshow";case
111:return"paste";case
112:return"pause";case
113:return"play";case
114:return"playing";case
115:return"pointercancel";case
116:return"pointerdown";case
117:return"pointerenter";case
118:return"pointerleave";case
119:return"pointerlockchange";case
120:return"pointerlockerror";case
121:return"pointermove";case
122:return"pointerout";case
123:return"pointerover";case
124:return"pointerup";case
125:return"popstate";case
126:return"progress";case
127:return"push";case
128:return"pushsubscriptionchange";case
129:return"ratechange";case
130:return"readystatechange";case
131:return"repeatEvent";case
132:return"reset";case
133:return"resize";default:return"resourcetimingbufferfull"}}if(45<=b)switch(b){case
45:return"DOMElementNameChanged";case
46:return"DOMFocusIn";case
47:return"DOMFocusOut";case
48:return"DOMNodeInserted";case
49:return"DOMNodeInsertedIntoDocument";case
50:return"DOMNodeRemoved";case
51:return"DOMNodeRemovedFromDocument";case
52:return"DOMSubtreeModified";case
53:return"downloading";case
54:return"drag";case
55:return"dragend";case
56:return"dragenter";case
57:return"dragleave";case
58:return"dragover";case
59:return"dragstart";case
60:return"drop";case
61:return"durationchange";case
62:return"emptied";case
63:return"end";case
64:return"ended";case
65:return"endEvent";case
66:return bt;case
67:return"fetch";case
68:return"focus";case
69:return"focusin";case
70:return"focusout";case
71:return"fullscreenchange";case
72:return"fullscreenerror";case
73:return"gamepadconnected";case
74:return"gamepaddisconnected";case
75:return"gotpointercapture";case
76:return"hashchange";case
77:return"input";case
78:return"install";case
79:return"invalid";case
80:return"keydown";case
81:return"keypress";case
82:return"keyup";case
83:return"languagechange";case
84:return"levelchange";case
85:return"load";case
86:return"loadeddata";case
87:return"loadedmetadata";case
88:return"loadend";default:return"loadstart"}switch(b){case
0:return"abort";case
1:return"activate";case
2:return"afterprint";case
3:return"animationend";case
4:return"animationiteration";case
5:return"animationstart";case
6:return"appinstalled";case
7:return"audioend";case
8:return"audioprocess";case
9:return"audiostart";case
10:return"beforeprint";case
11:return"beforeunload";case
12:return"beginEvent";case
13:return"blocked";case
14:return"blur";case
15:return"boundary";case
16:return"cached";case
17:return"canplay";case
18:return"canplaythrough";case
19:return"change";case
20:return"chargingchange";case
21:return"chargingtimechange";case
22:return"checking";case
23:return"click";case
24:return"close";case
25:return"complete";case
26:return"compositionend";case
27:return"compositionstart";case
28:return"compositionupdate";case
29:return"contextmenu";case
30:return"controllerchange";case
31:return"copy";case
32:return"cut";case
33:return"dblclick";case
34:return"devicechange";case
35:return"devicelight";case
36:return"devicemotion";case
37:return"deviceorientation";case
38:return"deviceproximity";case
39:return"dischargingtimechange";case
40:return"DOMActivate";case
41:return"DOMAttributeNameChanged";case
42:return"DOMAttrModified";case
43:return"DOMCharacterDataModified";default:return"DOMContentLoaded"}}function
au(b){return function(c){return function(d){return function(a){b.addEventListener(cw(c),aN(1,function(a){return k(d,a)}),!!a);return 0}}}}function
bj(a){return g[aI].resolve(a)}function
bk(a){return bj(a)===a?{content:a}:a}function
bl(a){var
b=aM(typeof
a)=="object"?1:0;if(b)var
c=a!==bb?1:0,d=c?a.content!==cu?1:0:c;else
var
d=b;return d?a["content"]:a}function
F(a){return bj(bk(a))}function
cx(a){var
b=bk(a);return g[aI].reject(b)}function
bm(a){return F(a)}function
v(a,b,c){var
d=a?a[1]:cx;return b.then(aN(1,function(a){return k(c,bl(a))}),aN(1,function(a){return k(d,bl(a))}))}function
m(c,b){return v(0,b,function(a){return F(k(c,a))})}function
bn(a){var
b=bc(function(a){return a},a2(a));function
c(a){return a}return m(function(a){return bd(c,a)},g[aI].all(b))}function
bo(b){return function(a){b.waitUntil(m(function(a){return a},a));return 0}}g[bF];g["navigator"];var
$=g["caches"],aW="static-v"+"1.4.8",bp=a2(ap(function(a){return"/scrabble-website"+a},cB));function
cy(a){return a}function
cz(a){return a}function
cA(a){return a}N(au(g)(78),function(a){u(cC);var
b=v(0,m(cA,$.open(T(aW))),function(b){return v([0,function(a){u(cD);bh(bi)(a);return v(0,bn(ap(function(c){return v([0,function(a){u("[Service Worker] cannot cache "+c);bh(bi)(a);return F(0)}],m(at,b.add(T(c))),bm)},a1(bp))),function(a){return F(0)})}],m(at,b.addAll(bc(T,bp))),bm)});bo(a)(b);g.skipWaiting();return 0},0);N(au(g)(1),function(a){u(cE);var
b=v(0,v(0,m(function(a){return bd(aM,a)},$.keys()),function(a){return bn(ap(function(a){return a!==aW?(u("[Service Worker] deleting cache "+a),m(cV,$.delete(T(a)))):F(1)},a))}),function(a){return m(at,g["clients"].claim())});return bo(a)(b)},0);N(au(g)(67),function(a){var
b=a["request"];u("[Service Worker] fetch "+aM(b["url"]));a.respondWith(m(cz,v(0,m(function(a){return a==bb?0:[0,a]},$.match(b)),function(a){if(a){var
c=a[1];u(cF);return F(c)}u(cG);return m(cy,g.fetch(b))})));return 0},0);aX(0);return}(globalThis));
